### ISSUE TITLE
software

### ISSUE THREAD

**Issue by carl1961** [rduart/TelsaCoilWinder#1]
you have a system to run your code?
https://github.com/carl1961/Arduino-Nano-Tesla-Coil-Winder

**Comment by rduart** [comment]
Yes, carl1961 I have a system to run the code on.   I have been refining the implementation for a while.   I am just getting ready to push the latest release.  I am currently able to wind coils about 350MM long with wire sizes from 26awg through 36awg.    I will make a point to upload some pictures and an overview document.    I also took a look at your github.   It's given me some ideas for improvement in my design.

**Comment by carl1961** [comment]
Thanks @rduart , I see your updates, but the HMI file is corrupt and won't load. maybe damaged from upload.
