### ISSUE TITLE
Corrupt files

### ISSUE THREAD

**Issue by carl1961** [rduart/TelsaCoilWinder#2]
Just so you may know,  CoilWinderV4.HMI, PCB_PCB_DVR8825V5_2024-05-12.png, and Schematic_DVR8825V5_2024-05-12.png  files or corrupt , nextion complained. But I still was able to get your code working great to do the coils, using your new code and older tft files, except for the new time est and turn totaler. of dozens of programs I tried, your program is the only one that worked and planned. Others out there only worked for their video, if you changed wire then their code did not work.
I did have to work with the counter to get it to count correctly for me. instead of using the AWG number I used your wire sized, you have handy converted to umm, just had to move the dot,  over to right 3 places 
10mm moved 10mm and coil nice and tight, excellent program! last picture was a second 10mm so 20mm total.

![image](https://github.com/rduart/TelsaCoilWinder/assets/3056821/09f07e96-6c70-40f5-835b-5f8646e67bae)

if(nAwg.val==26)
{
  page3.nTotalTurns.val=nCoil.val*1000/404
}
if(nAwg.val==28)
{
  page3.nTotalTurns.val=nCoil.val*1000/320
}
if(nAwg.val==30)
{
  page3.nTotalTurns.val=nCoil.val*1000/254
}
if(nAwg.val==32)
{
  page3.nTotalTurns.val=nCoil.val*1000/203
}
if(nAwg.val==34)
{
  page3.nTotalTurns.val=nCoil.val*1000/160
}
if(nAwg.val==36)
{
  page3.nTotalTurns.val=nCoil.val*1000/127
}
page 3

![Screenshot 2024-05-19 013721](https://github.com/rduart/TelsaCoilWinder/assets/3056821/5a38a598-9a8e-4065-b24a-3c29b0c4b481)

![Screenshot 2024-05-19 014525](https://github.com/rduart/TelsaCoilWinder/assets/3056821/94d8e773-e414-4281-b5a2-ed3fab36e08b)

![Screenshot 2024-05-19 015154](https://github.com/rduart/TelsaCoilWinder/assets/3056821/154205c1-dbd0-45f1-aefd-71bed98ddded)

![Screenshot 2024-05-19 015248](https://github.com/rduart/TelsaCoilWinder/assets/3056821/a8a41be6-26b2-417f-9ee7-12d3a52402da)

![WIN_20240519_02_24_59_Pro](https://github.com/rduart/TelsaCoilWinder/assets/3056821/568fbfef-7857-4aa6-8735-a46bdf2fed51)

![WIN_20240519_02_25_37_Pro](https://github.com/rduart/TelsaCoilWinder/assets/3056821/a8c9cd06-c252-4e9a-81ed-586bc999cc4b)

![WIN_20240519_02_25_57_Pro](https://github.com/rduart/TelsaCoilWinder/assets/3056821/9d2d7ce8-59d7-4b9d-a038-71b6939ca693)

![WIN_20240519_02_26_13_Pro](https://github.com/rduart/TelsaCoilWinder/assets/3056821/7b1ee994-3767-4d57-8e13-8b2f83012a42)

**Comment by carl1961** [comment]
It is GitHub desktop app corrupting our files, it corrupted my files (pictures too) weird, I manual uploaded through the web browser and download and file were ok, removed them with GitHub desktop app and resent them back up to the web, and all files was corrupted.

**Comment by rduart** [comment]
I am so glad to see that you were able to make my code work with your project.  I might know why the hmi file is getting corrupted.   Github is converting the carriage return to something nextion does not like.   Let me see what I can do.      Let me try converting the PNG to pictures and see if that help.

**Comment by rduart** [comment]
PNG files fixed.    Please see the .gitattributes they need to be set to binary.   Please take a look and let me know if you can see them now.   I will plan on pushing some pictures later this week.

**Comment by rduart** [comment]
HMI files fixed. Please see the .gitattributes needed a change. Please take a look and let me know if you can see it now.

**Comment by carl1961** [comment]
Yes all picture and HMI work, Thanks for finding the problem

**Comment by rduart** [comment]
Your welcome.  It's nice having some to collaborate with.

**Comment by carl1961** [comment]
On your new readme, link to Masculinity   is broke  and the library file like in your document's https://www.arduinolibraries.info/libraries/nextion
did not work for me, had to go back to the original nextion library 
 Thanks for your updates and your document, Enjoyed reading

I know every little about code, (I am a copy cat) Have you see this from Ray Livingstone, may fix your issues

https://forum.arduino.cc/t/nextion-v0-9-0-library-with-working-gui-events/596412
also someone archived his copy
https://github.com/matsekberg/ITEADLIB_Arduino_Nextion/archive/refs/tags/v0.9.0.zip
I will try too as I use software serial with this old version  MKS DLC 2.0 Arduino uno board ( Had 2 laying on the shelf)

**Comment by rduart** [comment]
Thanks for the QA check.   I fixed the links.  I have not seen the link from Ray, but I will take a look and make the update.   Its less than ideal to set or get variables multiple times.     I tried to add a lot of comments in the code to help anyone that might try to use my code.   I hope you found them helpful.   If you think of anything that is missing or needed, please let me know.    Keep up the good work.

**Comment by carl1961** [comment]
New code on my end does not populate the Turn total, Count, or est time. I am using a enhanced 3.5. but the math is working because I can still make a coil. except when finished it never prompts " Complete" and stays on page 3.
 I seen this while searching    maybe it makes since to you.

[javichuteck](https://forum.arduino.cc/u/javichuteck)
[Mar 2020](https://forum.arduino.cc/t/nextion-element-settext-problem-resolved/642706/3)post #3
The solution to my problem is the type conversion at the moment of marking the value of the String to the Nextion component.

In this case it is a component of type Text, and in calling the "setText" function with doing a type conversion, it works correctly.

Here is the example that worked for me:

clock_date_day.setText(theDay.c_str());
.c_str() is the conversion to the "NexText" component.

Thanks again and I hope it helps more people.

Greetings.


This is the serial monitor reading ( also I just remembered I used the guy Ray's 3 files), I will switch back and see it may be his files.

btVarnish
0
bHome
Found Low
started
bUnwind
0
bUnwind
0
btVarnish
0
bOffSetPlus
bOffSetMinus
+10
10
26
b2Next
24
2
Start Button pressed


It's Not Ray's files, here is serial monitor reading

bHome
Found Low
started
+10
10
26
b2Next
24
2
Start Button pressed

**Comment by carl1961** [comment]
Pictures of My code compared to yours, only added a few things, Serial Monitor and UnWinder 
Using your New HMI file, I like the new features, where you disabled buttons until you home. 

[CoilWinderV4_MKS_DLC2.0-V2_Pictures.zip](https://github.com/rduart/TelsaCoilWinder/files/15391522/CoilWinderV4_MKS_DLC2.0-V2_Pictures.zip)

**Comment by rduart** [comment]
Did you get the time, count and total count working again?      In the beginning, I was trying to use integers everywhere.   In some instances, I converted them to Text as you did.   This seems to fix the problem for the most part.   In some instances, I had to set the variables more than once.   You can see it in the code.    You might try to simply add the set method 2 or 3 in a row.    I feel there is something wrong with the nextion.h library.   Also please make sure that you always check the widgets number after making a change to the UI.    I really like the library, but it has some bugs that will drive you crazy.   I will take a look at your code.

**Comment by rduart** [comment]
Thinking about it more. Make sure to double check the widget numbers.   If you delete a widget from the UI, nextion renumbers the widgets.   Please make sure that they are the same in the Arduino code.   If the number is wrong gets and sets will not work.   I have had this problem many times.

**Comment by rduart** [comment]
Just redeployed my code, both the .HMI and .INO files and retested.  Its working  for me with the code on github,  I wanted to remove that as a possibility for your issue.

**Comment by rduart** [comment]
I am winding down for the day.    I took a look at you zip file with the HMI file,   Make sure that your object ID match between the HMI and the UNO.   
![hmi](https://github.com/rduart/TelsaCoilWinder/assets/10364651/995beea3-ff48-4ce5-9def-90553eb51338)
![ino](https://github.com/rduart/TelsaCoilWinder/assets/10364651/e08e9015-2559-4b92-acf8-68a99794b416)

**Comment by carl1961** [comment]
Thanks @rduart  . I started over with just your code and all is working, some how when adding back ground pictures, and my unwinder widget it messed things up.
![WIN_20240522_15_06_23_Pro](https://github.com/rduart/TelsaCoilWinder/assets/3056821/68606203-680d-471c-a8b3-afca3dbd08fc)

**Comment by carl1961** [comment]
Should this be *  , I find time estimate very close when I changed / with *

![Screenshot 2024-05-22 151812](https://github.com/rduart/TelsaCoilWinder/assets/3056821/2533b86b-b85f-4cfb-bba0-ac2db3bde70b)

**Comment by carl1961** [comment]
I found the issue, by doing changes, one at a time, when I got to using Software Serial   (so I would not have to keep unplugging Nextion display to upload code to Arduino uno, Software serial broke the Total, Count and est.

**Comment by rduart** [comment]
Glad to hear you have it working again.   I think I know why your time might be different than mine.   Did you changed the speed of the motors?    I timed several runs using a stopwatch.  I measured how many coils I could do in a minute and also how long it took me to create a 60mm coil.   I determine based on my motor speed and delays I could do about 17.42 turns a minute.  I could have rounded up of down ( rough estimate).   If your motor speed is higher and the estConstant variable is still set to 17.42 you would need to multiply.    You can derive a good, estimated coming at the problem from different directions.    You could do what I did and use an old fashion stopwatch to determine how many turns you can do in a minute, or you could time how long it takes to create a 60MM or 100mm coil.   totalturns/time=turn/min (estConstant)

**Comment by rduart** [comment]
Not sure about the software serial.   I can add it to mine and give it a test.  Just make sure when adding or removing UI components that you validate the object id.  They need to be the same in nextion and arduino.

**Comment by carl1961** [comment]
I think, and I may be wrong, 

just me trying to add a stepper for the unwinder motor breaks things.
dynamic memory  281 bytes free

software serial takes 117 bytes leaving only 164 bytes free Breaks things
adding a extra stepper takes 68 bytes  leaving only  213 bytes free  and even breaks things. 

Both I can live without, I already put me a switch on the Nextion TX wire to open it while uploading updates from the Uno.
and I already learned  the Unwinder motor on the Wire Spool needed it's own controller for different reasons, like wire spools diameters being different.

So your program is doing Great. Thanks for all your work.  I will close this issue thread.
